[tool.black]
line-length = 100
target-version = ['py38', 'py39']

[build-system]
requires = ["setuptools>=45", "wheel", "setuptools_scm>=6.2"]

[tool.setuptools_scm]
write_to = "dlc_generic_analysis/_version.py"