jobs:
  build:
    docker:
      - image: circleci/python:3.8.12
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - python/install-packages:
          args: tox
          pkg-manager: pip
      - run:
          command: |
            python3.8 -m tox

orbs:
  python: circleci/python@1.1.0
version: 2.1
workflows:
  main:
    jobs:
      - build