version: 2.1

executors:
  linux:
    docker:
      - image: ubuntu@18.04

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:202111-01
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libpulse-mainloop-glib0
            pip install -e .
            pip install tox
      - run:
          name: Test
          command: python -m tox
      - codecov/upload:
          file: './coverage.xml'
          token: a7a5df63-codcov-token-4278vh38

workflows:
  test:
    jobs:
      - build-and-test
