version: 2.1

executors:
  linux:
    docker:
      - image: ubuntu@18.04

orbs:
  python: circleci/python@1.2
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          command: pip install tox>=3.24.4
      - run:
          name: Run tests
          command: tox
      - codecov/upload:
          file: { { coverage_report_filepath } }

workflows:
  test:
    jobs:
      - build-and-test
